M48
; DRILL file {KiCad 9.0.3} date 2025-09-14T01:16:20+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-14T01:16:20+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X6.0177Y-3.6705
X6.0177Y-3.898
T2
X6.0984Y-4.3346
X6.0984Y-4.6496
M30
